# Generated by Django 4.1 on 2023-01-07 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("landingpage", "0003_event_logo_image_alter_company_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="alamat",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="link_instagram",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="link_linkedin",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
