# Generated by Django 4.1 on 2023-01-08 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("landingpage", "0004_event_alamat_event_link_instagram_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="alamat",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="company",
            name="bidang_usaha",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="company",
            name="link_instagram",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="company",
            name="link_linkedin",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="company",
            name="logo_image",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
