# Generated by Django 4.1 on 2023-01-08 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_massage_receiver'),
    ]

    operations = [
        migrations.AddField(
            model_name='massage',
            name='seen',
            field=models.BooleanField(default=False),
        ),
    ]
